### ISSUE TITLE
Evaluate on SemanticKITTI

### ISSUE THREAD

**Issue by JulesSanchez** [saltoricristiano/cosmix-uda#2] opened 2022-07-25 07:48 UTC
Hello and thanks for the great work and availability of the code:

If I wanted to reproduce the SemanticKITTI after adaptation results from the paper (table 2.).

I need to first run the adaption on my side and then the evaluation ? You are only providing the weights of the pre-training (before adaption) ? Do you plan on releasing adapted weights ?

Thank you.

**Comment by saltoricristiano** [comment] 2022-08-02 20:07
Hi @JulesSanchez,

thx for your interest in our work!
Yes, in order to reproduce our numbers you will need to start from the warmed up weights and repeat the adaptation procedure as described here https://github.com/saltoricristiano/cosmix-uda#target-adaptation but we may consider to upload also the weights after adaptation soon!
Did you already try to run the adaptation procedure?

Best, 
@saltoricristiano

**Comment by JulesSanchez** [comment] 2022-08-02 20:29
@saltoricristiano Hi did run the adaptation and found results very similar to the one described in the paper (only ran on SemanticKITTI so far, but also plan to launch on SemanticPOSS). The adaptation was a bit faster than what I worried initially.
Thank you for the availability !

Best.

**Comment by saltoricristiano** [comment] 2022-08-03 07:12
Perfect! Happy to hear you solved it by yourself!
Going to close the issue

**Closed as completed by saltoricristiano** 2022-08-03 07:12 UTC

**Comment by vijayM12** [comment] 2022-12-03 13:08
Hello @saltoricristiano I have read the Cosmix based on synLiDAR datset to semantickitti. I am working on symthetic data to real data point cloud translation and could not find the repo for "Transfer Learning from Synthetic to Real LiDAR Point Cloud for Semantic Segmentation". I would like to know if you have the idea on PCT algorithm of syn2real (Synlidar to semantickitti conversion) or can we do that using your present work Cosmix. (My research is on syn2real conversion). If you have the converted .bin files from syntheticto realistic data please help me since my research work needs the converted pointcloud files.
